"""
Generate (or remove) an HTML wrapper for each *.md file so it can be served
through the Claude Feedback server.

The wrapper loads marked.min.js from the skill's lib/, renders the markdown
client-side, then bootstraps feedback.js so the page is fully interactive.

Usage:
    python mdwrap.py <path>          # single .md OR a directory of .md files
    python mdwrap.py <path> --remove # delete generated wrapper(s) only
    python mdwrap.py <path> --recursive  # walk subdirectories

The generated .html files are stamped with a marker comment so this script can
identify and clean them without clobbering hand-written HTML.
"""
import argparse
import sys
from pathlib import Path

from _common import CSS_TAG, MDWRAP_MARKER as MARKER, ensure_feedback_dir, find_files


def _wrapper_html(md_name: str) -> str:
    """Return the full HTML wrapper for a given .md filename (basename only)."""
    return f"""{MARKER}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{md_name}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;0,700;1,400;1,600&family=JetBrains+Mono:wght@400;500&display=swap">
  <link rel="stylesheet" href="/lib/markdown.css">
  {CSS_TAG}
  <script id="cf-marked-script" src="/lib/marked.min.js" defer></script>
</head>
<body>
  <main class="markdown-page">
    <article id="cf-md-root" class="markdown-body"></article>
  </main>
  <script>
    window.CF_MARKDOWN_SRC = {repr(md_name)};
    (function () {{
      var root = document.getElementById("cf-md-root");
      // marked.min.js loads with `defer` so it doesn't block parsing, but that
      // only guarantees it runs before DOMContentLoaded -- not before this
      // fetch resolves. Wait for the script's own load event too, so a fast
      // local .md fetch can't call marked.parse() before `marked` exists.
      var markedReady = window.marked
        ? Promise.resolve()
        : new Promise(function (resolve) {{
            document.getElementById("cf-marked-script").addEventListener("load", resolve);
          }});
      Promise.all([
        fetch(window.CF_MARKDOWN_SRC).then(function (r) {{
          if (!r.ok) throw new Error("Failed to load " + window.CF_MARKDOWN_SRC + ": " + r.status);
          return r.text();
        }}),
        markedReady,
      ])
        .then(function (results) {{
          root.innerHTML = marked.parse(results[0]);
          var s = document.createElement("script");
          s.src = "/lib/feedback.js";
          s.defer = true;
          document.body.appendChild(s);
        }})
        .catch(function (err) {{
          root.innerHTML = "<pre style='color:red'>" + err + "</pre>";
          console.error(err);
        }});
    }})();
  </script>
</body>
</html>
"""


def wrap_one(md_path: Path) -> str:
    html_path = md_path.with_suffix(".html")
    if html_path.exists():
        existing = html_path.read_text(encoding="utf-8")
        if MARKER not in existing:
            return f"skipped — {html_path.name} exists and was not generated by mdwrap"
        # Already wrapped; re-generate (idempotent update)
    html_path.write_text(_wrapper_html(md_path.name), encoding="utf-8")
    return "wrapped"


def remove_one(md_path: Path) -> str:
    html_path = md_path.with_suffix(".html")
    if not html_path.exists():
        return "skipped (no wrapper found)"
    existing = html_path.read_text(encoding="utf-8")
    if MARKER not in existing:
        return f"skipped — {html_path.name} not generated by mdwrap (will not delete)"
    html_path.unlink()
    return "removed"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("path", help=".md file or directory containing .md files")
    ap.add_argument("--remove", action="store_true", help="delete generated wrapper(s) instead")
    ap.add_argument("--recursive", "-r", action="store_true", help="walk subdirectories")
    args = ap.parse_args()

    target = Path(args.path).resolve()

    if target.is_file():
        if target.suffix.lower() != ".md":
            print(f"ERROR: {target} is not a .md file", file=sys.stderr)
            return 1
        md_files = [target]
        root = target.parent
    elif target.is_dir():
        md_files = find_files(target, "*.md", args.recursive)
        root = target
        if not md_files:
            print(f"No *.md files found in {root}")
            return 0
    else:
        print(f"ERROR: {target} does not exist", file=sys.stderr)
        return 1

    action = remove_one if args.remove else wrap_one
    verb = "Removing wrappers for" if args.remove else "Wrapping"
    print(f"{verb} {len(md_files)} file(s):")
    for p in md_files:
        print(f"  {p.name}: {action(p)}")

    if not args.remove:
        ensure_feedback_dir(root)
        print(f"\nFeedback dir ready: {root / 'feedback'}")
        print(f"\nStart the server with:")
        print(f"  python ~/.claude/skills/make-pages-interactive/lib/server.py {root} --port 5050")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
